version: '3'

services:
  catalog.api:
    image: catalog.api
    build:
      context: ./Catalog.API
      dockerfile: Dockerfile

  orders.api:
    image: orders.api
    build:
      context: ./Orders.API
      dockerfile: Dockerfile
